apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cominow-cluster
  region: us-east-2
  version: "1.32"

managedNodeGroups:
  - name: cominow-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: false
    labels:
      role: worker
    tags:
      Environment: production
      Project: cominow

iam:
  withOIDC: true
